- job:
    name: monascalog-tempest-base
    parent: legacy-dsvm-base
    run: playbooks/legacy/monascalog-tempest-base/run.yaml
    post-run: playbooks/legacy/monascalog-tempest-base/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/monasca-agent
      - openstack/monasca-api
      - openstack/monasca-common
      - openstack/monasca-grafana-datasource
      - openstack/monasca-notification
      - openstack/monasca-persister
      - openstack/monasca-statsd
      - openstack/monasca-thresh
      - openstack/monasca-ui
      - openstack/python-monascaclient
      - openstack/tempest
      - openstack/monasca-log-api
      - openstack/monasca-kibana-plugin
      - openstack/monasca-tempest-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^.*\.md$
      - ^doc/.*$
      - ^releasenotes/.*$

- job:
    name: monascalog-tempest
    parent: monascalog-tempest-base

- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - monascalog-tempest
    gate:
      queue: monasca
      jobs:
        - monascalog-tempest
