.. note:: The Log API v2 has been DEPRECATED in the Mitaka release.  The
    migration path is to use the `Log API v3
    <https://developer.openstack.org/api-ref/monitoring-log-api/#logs>`_ instead of version 2
    of the API.  The Log API v2 will ultimately be removed, following the
    `OpenStack standard deprecation policy
    <https://governance.openstack.org/reference/tags/assert_follows-standard-deprecation.html>`_.
