.. note:: The Log API v2 has been DEPRECATED in the Mitaka release.  The
    migration path is to use the `Log API v2
    <http://developer.openstack.org/api-ref/monasca-log-api/v3/>`_ instead of version 2
    of the API.  The Log API v1 will ultimately be removed, following the
    `OpenStack standard deprecation policy
    <https://governance.openstack.org/reference/tags/assert_follows-standard-deprecation.html>`_.
